// Code generated by go generate; DO NOT EDIT. 
package Front 

type HTMLPAGE string

const HTMLAccount HTMLPAGE = `<main application="account">

    <section page="index">
        <div class="middle">

            <input class="genSeed" type="submit" value="CREATE NEW WALLET">

            <hr>

            <input class="importSeed" type="submit" value="IMPORT SEEDFY">

        </div>
    </section>

    <section page="generate">
        <div class="middle">

            <label for="seed">COPY YOUR SEEDFY</label>
            <textarea class="seed" rows="3" spellcheck="false"></textarea>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="import">
        <div class="middle">

            <label for="seed">ENTER YOUR SEEDFY</label>
            <textarea class="seed" rows="3" spellcheck="false"></textarea>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="password">
        <div class="middle">

            <label for="pass">PASSWORD</label>
            <input class="password" type="password">

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="address">
        <div class="middle">

            <label for="seed">CHOOSE YOUR ADDRESS</label>
            <select type="list" class="address">
            </select>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>



</main>
` 
const HTMLBase HTMLPAGE = `<html window-frame="transparent" resizeable>
<head>
    <meta charset="UTF-8">
    <title>Nanollet</title>

    <link rel="stylesheet" type="text/css" href="../css/icons.css">
    <link rel="stylesheet" type="text/css" href="icons.css">
</head>
<body class="notconnected">

<section class="account" role="window-caption">
    <icon class="logo-nano"></icon>
    <div class="ammount">0.00000</div>
</section>

<section class="apps">
    <aside class="app">
        <button id="nanofy">Nanofy</button>
        <button id="nanollet">Nanollet</button>
    </aside>
</section>

<section class="control">
</section>

<section class="dynamic">
</section>

<section class="notification">
    <!--<button class="notification"></button>-->
</section>
<script type="text/tiscript">
    class DropZone : Element {
      event drag (evt) {
        if(evt.draggingDataType == #file) {
          return true;
        }
      }
      event drop (evt) {
        if(evt.draggingDataType == #file) {
          this.parent.select(".filepath").value = evt.dragging
          this.select(".name").value = evt.dragging.split("\\")[evt.dragging.split("\\").length-1]

          return true;
        }
      }
    }

</script>
<button  role="window-close">
    <icon id="end" class="icon-exit"></icon>
</button>
</body>
</html>` 
const HTMLNanofy HTMLPAGE = `<main application="nanofy">

    <section page="sign">
        <div class="middle">

            <label for="file">FILE</label>
            <dropzone type="file" name="file"><div class="content name">Drop the file here</div> </dropzone>
            <textarea type="hidden" class="filepath"></textarea>

            <input class="continue" type="submit" value="SIGN">

        </div>
    </section>

    <section page="verify">
        <div class="middle">

            <label for="file">FILE</label>
            <dropzone type="file" name="file"><div class="content name">Drop the file here</div> </dropzone>
            <textarea type="hidden" class="filepath"></textarea>

            <label for="address">ADDRESS</label>
            <textarea spellcheck="false" class="address" rows="2"></textarea>

            <input class="continue" type="submit" value="VERIFY">

        </div>
    </section>

</main>
` 
const HTMLNanollet HTMLPAGE = `<main application="nanollet">

    <section page="wallet">
        <div class="middle">

            <label for="address">ADDRESS</label>
            <textarea spellcheck="false" class="address" rows="2"></textarea>

            <label for="address">AMOUNT</label>
            <div class="amountbox">
                <input type="text" class="whole" novalue="0" maxlength="7" filter="0~9">
                <input type="text" class="divider" readonly value=".">
                <input type="text" class="decimal" novalue="000000" maxlength="6" filter="0~9">
            </div>

            <input class="continue" type="submit" value="SEND PAYMENT">

        </div>
    </section>


    <section page="receive">
        <div class="middle">

            <label for="address">YOUR ADDRESS</label>
            <textarea class="address" rows="2" spellcheck="false"></textarea>

        </div>
    </section>

    <section page="list">
        <div class="middle">

            <label>BALANCE</label>
            <div class="box fullamoutbox">
                <div class="item fullamount"></div>
            </div>

            <label>TRANSACTIONS</label>
            <div class="box txbox">
                <div class="item">
                    No transactions were found. :(
                </div>
            </div>

        </div>
    </section>


</main>
` 
