// Code generated by go generate; DO NOT EDIT.
// +build !js

package Front


var HTMLAccount = HTMLPAGE(`<main application="account">

    <section page="index">
        <div class="middle">

            <input class="genSeed" type="submit" value="CREATE NEW WALLET">

            <hr>

            <input class="importSeed" type="submit" value="IMPORT SEEDFY">

        </div>
    </section>

    <section page="generate">
        <div class="middle">

            <label>COPY YOUR SEEDFY</label>
            <textarea class="seed" rows="3" spellcheck="false"></textarea>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="import">
        <div class="middle">

            <label>ENTER YOUR SEEDFY</label>
            <textarea class="seed" rows="3" spellcheck="false"></textarea>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="password">
        <div class="middle">

            <label>PASSWORD</label>
            <input class="password" type="password">

            <label>2FA</label>
            <label class="checkbox"><input class="ask2fa" type="checkbox" value="true">Ask for two factor authentication</label>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>

    <section page="mfa">
        <div class="middle">

            <label>SCAN WITH YOUR NANOLLET 2FA</label>
            <div class="qrcode"></div>

            <input class="continue" type="submit" disabled value="CONTINUE">

        </div>
    </section>

    <section page="address">
        <div class="middle">

            <label>CHOOSE YOUR ADDRESS</label>
            <div>
                <button class="next"><icon class="icon-next" /></button>
                <button class="previous"><icon class="icon-previous" /></button>
                <select type="list" class="address box">
                </select>
            </div>

            <input class="continue" type="submit" value="CONTINUE">

        </div>
    </section>


</main>
`)
var HTMLBase = HTMLPAGE(`<html window-frame="solid" window-blurbehind="light" resizeable>
<head>
    <meta charset="UTF-8">
    <title>Nanollet</title>

    <link rel="stylesheet" type="text/css" href="../css/style.css">
</head>
<body class="notconnected">


<header role="window-caption">
    <section class="logo">
        NANOLLET
    </section>
    <section class="account">
        <icon class="logo-nano"/>
        <div class="ammount"></div>
        <button role="window-close">
            <icon id="end" class="icon-exit"></icon>
        </button>
    </section>
</header>

<section class="control">
</section>

<section class="dynamic">
</section>

<section class="notification">
    <!--<button class="notification"></button>-->
</section>
<!--
    Custom Input - DropZone:
    This input is used in "Nanofy" to select the file, it
 -->
<script type="text/tiscript">
    class DropZone : Element {
      event click() {
         var fn = view.selectFile(#open, "All Files (*.*)|*.*");
         if( fn ) {
          this.parent.select(".filepath").value = fn
          this.select(".name").value = fn.split("/")[fn.split("/").length-1]
          return true;
         }
      }
      event drag (evt) {
        if(evt.draggingDataType == #file) {
          return true;
        }
      }
      event drop (evt) {
        if(evt.draggingDataType == #file) {
          this.parent.select(".filepath").value = evt.dragging
          this.select(".name").value = evt.dragging.replace("\\", "/").split("/")[evt.dragging.replace("\\", "/").split("/").length-1]
          return true;
        }
      }
    }
</script>
</body>
</html>`)
var HTMLNanofy = HTMLPAGE(`<main application="nanofy">

    <section page="sign">
        <div class="middle">

            <label for="file">FILE</label>
            <dropzone type="file" name="file"><div class="content name">Drop the file here</div> </dropzone>
            <textarea type="hidden" class="filepath"></textarea>

            <input class="continue" type="submit" value="SIGN">

        </div>
    </section>

    <section page="verify">
        <div class="middle">

            <label for="file">FILE</label>
            <dropzone type="file" name="file"><div class="content name">Drop the file here</div> </dropzone>
            <textarea type="hidden" class="filepath"></textarea>

            <label for="address">ADDRESS</label>
            <textarea spellcheck="false" class="address" rows="2"></textarea>

            <input class="continue" type="submit" value="VERIFY">

        </div>
    </section>

</main>
`)
var HTMLNanollet = HTMLPAGE(`<main application="nanollet">

    <section page="send">
        <div class="middle">

            <label for="address">ADDRESS</label>
            <textarea spellcheck="false" class="address" rows="2"></textarea>

            <label for="address">AMOUNT</label>
            <div class="amountbox">
                <input type="text" class="whole" novalue="0" maxlength="7" filter="0~9">
                <input type="text" class="divider" readonly value=".">
                <input type="text" class="decimal" novalue="000000" maxlength="6" filter="0~9">
            </div>

            <input class="continue" type="submit" value="SEND PAYMENT">

        </div>
    </section>

    <section page="receive">
        <div class="middle">

            <label for="address">YOUR ADDRESS</label>
            <textarea class="address" rows="2" spellcheck="false"></textarea>

        </div>
    </section>

    <section page="representative">
        <div class="middle">

            <label for="address">ADDRESS</label>
            <textarea spellcheck="false" class="address" rows="2"></textarea>

            <input class="continue" type="submit" value="CHANGE REPRESENTATIVE">

        </div>
    </section>

    <section page="history">
        <div class="middle">

            <label>BALANCE</label>
            <div class="box fullamoutbox">
                <div class="item fullamount"></div>
            </div>

            <label>TRANSACTIONS</label>
            <div class="box txbox">
                <div class="item">
                    No transactions were found. :(
                </div>
            </div>

        </div>
    </section>


</main>
`)
